Revert "Replacing java 13 with java 14"
This reverts commit 14ecba03402a431d17d27931564d601e31a3a5a7.

Sonar is broken with Java 14:
https://community.sonarsource.com/t/issue-java-14-java-lang-noclassdeffounderror-java-util-jar-pack200/21853